version: "3.8"

services:

  configserver:
    image: pblgllgs/configserver-eb:latest
    ports:
      - "8071:8071"
    networks:
      - eb-network

  accounts:
    image: pblgllgs/account-eb:latest
    ports:
      - "8080:8080"
    networks:
      - eb-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  loans:
    image: pblgllgs/loans-eb:latest
    ports:
      - "8090:8090"
    networks:
      - eb-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: pblgllgs/cards-eb:latest
    ports:
      - "9000:9000"
    networks:
      - eb-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
networks:
  eb-network:
